const BASE_URL = 'http://192.168.75.40:8080';

// const BASE_URL = process.env.BASE_URL;
export const API = {
    LOGIN: `${BASE_URL}/user/login`,
    PUNCHIN: `${BASE_URL}/user/punch-in`,
    SCRUM_POPUP: `${BASE_URL}/user/scrum`,
    GET_ATTENDANCE: `${BASE_URL}/user/get_punch`,
    ATTENDANCE_FILTER: `${BASE_URL}/user/search-report`,
    SELECT_MANAGER: `${BASE_URL}/user/get_assign_sup_man`,
    ADD_DSR: `${BASE_URL}/user/add_dsr`,
    GET_DSR: `${BASE_URL}/user/get_dsr`,
    GET_DSR_LIST: `${BASE_URL}/user/get_dsr_list`,
    GET_DSR_REPORT: `${BASE_URL}/user/get_submited_data`,
    DSR_INFO: `${BASE_URL}/user/dsr_info`,
    EDIT_DSR: `${BASE_URL}/user/edit_dsr`,
    CHANGE_PASSWORD_PROFILE: `${BASE_URL}/user/change_password`,
    PROFILE: `${BASE_URL}/user/get-user-info`,
    EDIT_PROFILE: `${BASE_URL}/user/edit-profile`,
    SCRUM_REPORTS: `${BASE_URL}/user/search-scrum`,
    QA_RESPONSE: `${BASE_URL}/user/get_notes`,
    GET_TASKS: `${BASE_URL}/user/get-tasks`,
    UPDATE_TASK_STATUS: `${BASE_URL}/user/update_status_tasks`,
    PROJECT_SUPERVISOR: `${BASE_URL}/user/get_project_supervisor`,
    ADD_QA_NOTES: `${BASE_URL}/user/add_qa_notes`,
    GET_SCRUM_DATA: `${BASE_URL}/user/get_scrum_data`,
    GET_CC: `${BASE_URL}/user/get_cc`,
    IS_PROJECT_SUBMITTED: `${BASE_URL}/user/is_project_submited`,
    PUNCH_OUT: `${BASE_URL}/user/punch_out`,
    ACTIVE_PROJECTS: `${BASE_URL}/user/get_all_active_projects`,
    ASSIGNED_TASKS: `${BASE_URL}/user/get_tasks_acc_status`,
    ASSIGNED_BY_NAME: `${BASE_URL}/user/getAssignedByUser`,
    CHECK_DSR: `${BASE_URL}/user/check_dsr`,
    DEADLINES_MISSED: `${BASE_URL}/user/get_missed_deadline`,
    FORGOT_PASSWORD: `${BASE_URL}/user/forgotpassword`,
    RESET_PASSWORD: `${BASE_URL}/user/reset-password`,
    LEAVE_TYPE: `${BASE_URL}/user/leaveType`,
    LEAVE_APPLY: `${BASE_URL}/user/leave`,
    GET_ALL_LEAVES: `${BASE_URL}/user/getleavestatus`,
    VIEW_LEAVE_BY_ID: `${BASE_URL}/user/view/leave`,
    NOTIFICATIONS: `${BASE_URL}/user/unreadandall`,
    GETTOP10NOTIFICATIONS: `${BASE_URL}/user/getTop10Notifications`,
    ALLMARKASREADANDDELETE: `${BASE_URL}/user/allmarkandreaddelete`,
    APPLYWEEKENDWORKING: `${BASE_URL}/user/weekend_work/apply`,
    GETAPPLYWEEKENDWORKING: `${BASE_URL}/user/weekend_work/getAlldata`,
    WEEKENDWORKINGPUNCHIN: `${BASE_URL}/user/weekend_work/check_approval`,
    // GETCALENDER: `${BASE_URL}/user/get_calender`
    GETCALENDER: `${BASE_URL}/user/get_calender`,
    MARKASREADTOP10NOT: `${BASE_URL}/user/mark_as_read`,
    WORKPLACESTATUS: `${BASE_URL}/user/workplace_status`
};
